

















namespace rw
{
namespace graphics
{
namespace core
{




enum RwgObjectType
{
    RWGOBJECTTYPE_NA = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE0) & 0xff)),

    RWGOBJECTTYPE_VIEWPORTPARAMETERS = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE1) & 0xff)),
    RWGOBJECTTYPE_SCISSORRECTPARAMETERS = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE2) & 0xff)),
    RWGOBJECTTYPE_CLEARCOLORPARAMETERS = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE3) & 0xff)),
    RWGOBJECTTYPE_CLEARDEPTHSTENCILPARAMETERS = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE4) & 0xff)),
    RWGOBJECTTYPE_DRAWINDEXEDPARAMETERS = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE5) & 0xff)),
    RWGOBJECTTYPE_DRAWPARAMETERS = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE6) & 0xff)),
    RWGOBJECTTYPE_PIXELBUFFER = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE7) & 0xff)),
    RWGOBJECTTYPE_TEXTURE = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE8) & 0xff)),
    RWGOBJECTTYPE_VERTEXDESCRIPTOR = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xE9) & 0xff)),
    RWGOBJECTTYPE_VERTEXBUFFER = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xEA) & 0xff)),
    RWGOBJECTTYPE_INDEXBUFFER = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xEB) & 0xff)),
    RWGOBJECTTYPE_PROGRAMBUFFER = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xEC) & 0xff)),
    RWGOBJECTTYPE_STATEBUFFER = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xED) & 0xff)),
    RWGOBJECTTYPE_PROGRAMSTATEBUFFER = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xEE) & 0xff)),
    RWGOBJECTTYPE_PROGRAMSTATES = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xEF) & 0xff)),

    RWGOBJECTTYPE_MESHSTATE = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xF1) & 0xff)),
    RWGOBJECTTYPE_TEXTURESTATE = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xF2) & 0xff)),
    RWGOBJECTTYPE_RENDERTARGETSTATE = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xF3) & 0xff)),
    RWGOBJECTTYPE_BLENDSTATE = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xF4) & 0xff)),
    RWGOBJECTTYPE_DEPTHSTENCILSTATE = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xF5) & 0xff)),
    RWGOBJECTTYPE_RASTERIZERSTATE = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xF6) & 0xff)),
    RWGOBJECTTYPE_PROGRAMSTATEHANDLE = ((((rwCOMPONENTID_GRAPHICS) & 0xff) << 16) | ((0xF8) & 0xff)),




    RWGOBJECTTYPE_FORCEENUMSIZEINT = ((int32_t)((~((uint32_t)0))>>1))
};

}
}
}
